name: digital_dairy
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.3.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_localization: ^0.3.3
  fpdart: ^1.1.1
  get_it: ^8.0.3
  go_router: ^16.0.0
  google_fonts: ^7.0.2
  google_nav_bar: ^5.0.7
  hydrated_bloc: ^10.1.1
  i18n_extension: ^15.0.5
  image_picker:
  intl:
  logging: ^1.3.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^12.0.1
  printing: ^5.14.2
  supabase_flutter: ^2.9.1
  uuid:

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hyper_lint:

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon_digi_.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
